### PR TITLE
Add weDigBio background image #170

### PR DESCRIPTION
**Pull request by rafelafrance**
This a temporary image for the landing page during weDigBio event

### CODE REVIEW

**Comment by mcbouslog** [comment]
LGTM! 
Should I merge and deploy today, or wait until closer to Thursday?

**Comment by robgur** [comment]
Wait till Thursday night, please!  Can someone show a screenshot please?
Just so we can see it?

**Comment by rafelafrance** [comment]
screenshot from 2016-10-17 15-43-36

**Comment by robgur** [comment]
It looks awesome.  Thanks for the great work.
Launch Thursday EOD?
Best, Rob

**Comment by mcbouslog** [comment]
Sorry just to clarify - event starts Thursday, October 20th? If so, should I launch the new background image Wednesday evening, October 19th, or end-of-day Thursday?

**Comment by MobileMaggie** [comment]
End of day Wednesday please, as the event will be launching Thursday morning starting first in Australia...

**Comment by mcbouslog** [comment]
Sounds good, will do!

**Comment by robgur** [comment]
Michael?  Do we want to start on Wednesday evening?  That would work for
me.
Best, -r

**Comment by denslowm** [comment]
Yes, I was going to suggest the same (Wednesday). 

I think enough NFN regulars already know it's coming so a little early in the U.S. shouldn't be a problem.

**Pull request merged**
