### PR TITLE
Update field book

### PR DESCRIPTION
**Pull request by rafelafrance**
Mark: Please make sure the code is reasonable.

Jordan: Please make sure the look and feel is a close approximation of what you expect it to be.

### CODE REVIEW

**Comment by robgur** [comment]
We are hoping to get a blog post out about the changes to the look and
feel tomorrow, so people know there is going to be a site update, and then
we plan to launch this Thursday am.  If that timing looks poor for any
reason, give a holler!  Jordan, if you make big changes, can you let us
know.  Small ones are fine, just want to be sure we all know what will land
on Thursday (we hope).  Thanks to Jordan and Rafe for all the effort on
this!!!

**Comment by mcbouslog** [comment]
- this is deployed to the staging (formerly beta) site https://relaunch.notesfromnature.org/

I see none of these as reasons not to deploy to production before tomorrow, but:
1. the Collaborator footer overlaps the About page content in Firefox
2. is it intended the Completed Expeditions background image repeats? looks good to me, just making sure.

Otherwise looks ready to merge to me.

**Comment by rafelafrance** [comment]
These are both problems that appear in FireFox. I'd like to fix them before we deploy. Especially issue 1 that's a mess. Thanks for finding these before the deploy.

**Comment by robgur** [comment]
Thanks, all.  Rafe, if you have time, great.  I was hoping Jordan could
take a peek too if she has time.

**Comment by rafelafrance** [comment]
I have a fix for the first issue. However, I'm having trouble replicating the second one locally, so the fix that I put in may or may not work.

**Comment by robgur** [comment]
I have a few quick edits but nothing huge. Should I post it as an issue on
github or just send details here?

___

_J.W. Martin_
_Citizen Science Visual Design Lead_
Zooniverse | Adler Planetarium
1300 S Lake Shore Drive
Chicago, IL 60605

**Comment by robgur** [comment]
Send deets here is fine by me.  THANKS!

**Comment by robgur** [comment]
Just a few little alignment details that should result in huge changes.

Best,

J

___

_J.W. Martin_
_Citizen Science Visual Design Lead_
Zooniverse | Adler Planetarium
1300 S Lake Shore Drive
Chicago, IL 60605

**Comment by robgur** [comment]
I meant "that _shouldn't_ result in a huge change"

___

_J.W. Martin_
_Citizen Science Visual Design Lead_
Zooniverse | Adler Planetarium
1300 S Lake Shore Drive
Chicago, IL 60605

**Comment by robgur** [comment]
Jordan, you might look at the latest updates from Rafe --- we decided to
make the design on the main splash page much closer to your original
design.  The design you sent back for at least the splash page is our old
one.

-r

**Pull request closed without merging**
