### PR TITLE
New badges

### LINKED ISSUE #224: add 5000 badge for herbarium
Please add the following badge for when I user reaches 5000 transcriptions.
a 2500 badge will come at a later date.

badge-mature_grove

### LINKED ISSUE #225: add Fungi badges
We currently have 3 fungi badges that will relate to a new group called Fungi

1. spore
2. mycelium
3. mushroom

@robgur I am thinking that we make these consistent with the insect badges. That is the interval 1, 25 and 100. Do you concur? 

spore
mycelium
mushroom

### PR DESCRIPTION
**Pull request by rafelafrance**
Fixes #224 and Fixes #225 

Fungi badges where already there.

### CODE REVIEW

**Comment by denslowm** [comment]
Sorry about that!
Do we already have a group icon for fungi? I was planning to get something put together today on that.

**Comment by rafelafrance** [comment]
Yes we do

screenshot from 2017-03-22 14-34-07

**Comment by denslowm** [comment]
Perfect!

**Review by mcbouslog — APPROVED** [review]

**Comment by mcbouslog** [comment]
Closes #173

**Comment by mcbouslog** [comment]
I'll deploy first-thing Thursday AM.

**Pull request merged**
