### PR TITLE
Site redesign

### PR DESCRIPTION
**Pull request by rafelafrance**
This is phase one of the redesign. You don't have to merge this yet but I'd like to get some input on if this is "merge-able".

### CODE REVIEW

**Comment by mcbouslog** [comment]
Looking great!

Should the Field Book Recent Expeditions and Recent Transcription tiles have titles/text?

There might be some quirky behavior unrelated to the recent code, but I've deployed `update-field-book` to https://relaunch.notesfromnature.org if you'd like to check it out.

I see the following warnings in the console, just warnings though, not sure urgency of deploy vs wanting to address:
1. Home/Landing - `warning.js?0260:44Warning: You are manually calling a React.PropTypes validation function for the 'path' prop on 'Route'.`
2. Field Book - `Warning: Unknown prop 'zIndex' on <a> tag.`

**Comment by robgur** [comment]
Mark -- Hold on any merge.  We have some minor to moderate changes still
coming.
Best, Rob

**Comment by rafelafrance** [comment]
I'm trying to squash all of the warnings and this looks like one that I should. I'll take care of it. I've gotten some feedback on the look and feel too. So i'll close this request and get back to you with the GUI enhancements and a warnings squash.

The "no text" on the Field Book thing is... by design and it passed GUI review so I think we're OK there.

**Comment by jwbmartin** [comment]
Hey team,
Looking great so far!!! Do you mind if I pop in with just a few tips to polish off the design?

**Comment by robgur** [comment]
Jordan, yeah, but we are in the midst of a small refactoring based on
input from my lab --- so lets hold off until Rafe finishes the next
iteration, and then we can go from there?

Best, Rob

**Comment by jwbmartin** [comment]
Sounds good!

**Pull request closed without merging**
