### PR TITLE
Update field book

### PR DESCRIPTION
**Pull request by rafelafrance**
Redesign of the field book. Issue #90

### CODE REVIEW

**Comment by denslowm** [comment]
@wgranger Is this something you can do while Mark is out of town? We are just trying to get an ETA since we want to post some blogs about the upcoming style changes to the site.

**Comment by wgranger** [comment]
Right. Are you trying to get this merged by the end of the week? I noticed this popped up the other day and forgot to ask Mark about it. Let me take a look at the PR and get back to you. I’ll ping Jordan too to get her input.

**Comment by wgranger** [comment]
@rafelafrance Is there a reason in `field-book.jsx` that `doDispatches` is called in `componentDidUpdate`? I think the reason the API call for classifications and preferences is made continuously is because `doDispatches` is updating the component when it is called and thus run infinitely on `componentDidUpdate`.

**Comment by rafelafrance** [comment]
Yes, and this is not ideal, if you hit page reload when in the Field Book the information will not display. I already have an issue for this #96. I am waiting to accrue some time so that I can find a better way to handle  this.

**Pull request closed without merging**
